/**
 * Runtime migration runner — NATIVE (iOS/Android).
 *
 * Drizzle's expo migrator applies the bundled migrations on app start. Call
 * `useRunMigrations()` in the root layout and gate rendering on `success`.
 */
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

// Import the .native module explicitly: Metro would resolve './client' to it
// on native anyway, but tsc doesn't know platform extensions and would check
// this file against the async web client, whose DB type the expo migrator
// rejects.
import { db } from './client.native';
// Generated by `drizzle-kit generate` (driver: 'expo').
import migrations from './migrations/migrations';

export function useRunMigrations() {
  return useMigrations(db, migrations);
}
