/**
 * Runtime migration runner.
 *
 * Drizzle's expo migrator applies the bundled migrations on app start. Call
 * `useRunMigrations()` in the root layout and gate rendering on `success`.
 */
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

import { db } from './client';
// Generated by `drizzle-kit generate` (driver: 'expo').
import migrations from './migrations/migrations';

export function useRunMigrations() {
  return useMigrations(db, migrations);
}
